INSERT INTO BOOK(name) VALUES ('Book 1');
INSERT INTO BOOK(name) VALUES ('Book 2');
INSERT INTO BOOK(name) VALUES ('Book 3');
INSERT INTO BOOK(name) VALUES ('Book 4');
INSERT INTO BOOK(name) VALUES ('Book 5');
